// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0mj8xLoZGtBPrr2p_33pEh24CbFZSWA0',
    appId: '1:28066857960:web:1b9437f250198ecc84da5d',
    messagingSenderId: '28066857960',
    projectId: 'mustdo-fa1a2',
    authDomain: 'mustdo-fa1a2.firebaseapp.com',
    storageBucket: 'mustdo-fa1a2.appspot.com',
    measurementId: 'G-1BG6GHD0LE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0FdF7Wx6kPklAZ55rcFZco043NQ2VdtI',
    appId: '1:28066857960:android:f426c62cefacbae384da5d',
    messagingSenderId: '28066857960',
    projectId: 'mustdo-fa1a2',
    storageBucket: 'mustdo-fa1a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpYvj9mfYolBH2KeVhfxtsnBVxVJbPLv4',
    appId: '1:28066857960:ios:14de21e5c7bbe14784da5d',
    messagingSenderId: '28066857960',
    projectId: 'mustdo-fa1a2',
    storageBucket: 'mustdo-fa1a2.appspot.com',
    iosClientId: '28066857960-1bt36ceel4h5el9650jg3vvsha4ece83.apps.googleusercontent.com',
    iosBundleId: 'com.example.mustDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpYvj9mfYolBH2KeVhfxtsnBVxVJbPLv4',
    appId: '1:28066857960:ios:14de21e5c7bbe14784da5d',
    messagingSenderId: '28066857960',
    projectId: 'mustdo-fa1a2',
    storageBucket: 'mustdo-fa1a2.appspot.com',
    iosClientId: '28066857960-1bt36ceel4h5el9650jg3vvsha4ece83.apps.googleusercontent.com',
    iosBundleId: 'com.example.mustDo',
  );
}
